GRANT LOGMINING TO C##CDC_REMEDIATION CONTAINER=ALL;
GRANT SET CONTAINER TO C##CDC_REMEDIATION CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_LOGMNR TO C##CDC_REMEDIATION CONTAINER=ALL;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO C##CDC_REMEDIATION CONTAINER=ALL;
GRANT SELECT ON SYS.V_$LOG TO C##CDC_REMEDIATION CONTAINER=ALL;
GRANT SELECT ON SYS.V_$LOGFILE TO C##CDC_REMEDIATION CONTAINER=ALL;
GRANT SELECT ON SYS.V_$LOGMNR_CONTENTS TO C##CDC_REMEDIATION CONTAINER=ALL;
